# explorando ddl
DROP DATABASE IF EXISTS MANIPULATION;
CREATE DATABASE IF NOT EXISTS MANIPULATION;
SET SQL_SAFE_UPDATES = 0;

USE MANIPULATION;
CREATE TABLE IF NOT EXISTS BANK_ACCOUNTS (
	ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
    AG_NUM INT NOT NULL,
    AC_NUM INT NOT NULL,
    SALDO FLOAT,
    CONSTRAINT U_BANKACCOUNTS_IDENTIFICATIONACCOUNT UNIQUE (AG_NUM, AC_NUM)
);

CREATE TABLE IF NOT EXISTS BANK_CLIENTS(
	ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ACCOUNT INT,
    CPF VARCHAR(11) NOT NULL,
    RG VARCHAR(9) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    RENDA_MENSAL FLOAT,
    CONSTRAINT U_BANKCLIENTS_CLIENTACCOUNT UNIQUE (CLIENT_ACCOUNT),
    CONSTRAINT FK_BANKCLIENTS_BANKACCOUNTS FOREIGN KEY (CLIENT_ACCOUNT)
		REFERENCES BANK_ACCOUNTS(ID_ACCOUNT) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS BANK_TRANSACTIONS (
	ID_TRANSACTION INT AUTO_INCREMENT PRIMARY KEY,
    OCORRENCIA DATETIME,
    STATUS_TRANSACTION VARCHAR(20),
    VALOR_TRANFERIDO FLOAT,
    SOURCE_ACCOUNT INT,
    DESTINATION_ACCOUNT INT,
    CONSTRAINT FK_BANKTRANSACTIONS_BANKACCOUNTS_SOURCE FOREIGN KEY (SOURCE_ACCOUNT)
		REFERENCES BANK_ACCOUNTS(ID_ACCOUNT) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_BANKTRANSACTIONS_BANKACCOUNTS_DESTINATION FOREIGN KEY (DESTINATION_ACCOUNT)
		REFERENCES BANK_ACCOUNTS(ID_ACCOUNT) ON DELETE CASCADE ON UPDATE CASCADE
);

ALTER TABLE BANK_CLIENTS ADD EMAIL VARCHAR(60);
ALTER TABLE BANK_CLIENTS DROP EMAIL;
-- ALTER TABLE ADD CONSTRAINT 

DESC BANK_ACCOUNTS;
DELETE FROM BANK_ACCOUNTS;
INSERT INTO BANK_ACCOUNTS VALUES (0,0,2,500),
								 (0,0,3,300),
								 (0,0,5,10000),
								 (0,0,7,-5.89),
								 (0,0,11,0);
DESC BANK_CLIENTS;
INSERT INTO BANK_CLIENTS VALUES (0,1,'12345678910','0','JOSE SILVA','Av. Paulo Portela, nº 210, Jd. Paulista – 3º andar, Sala 311' ,5000),
								 (0,2,'12345678911','1','MASINA SOUZA','Rua Manoel Honorato dos Santos, Nº 195 – Jd. Alterópolis (CEP: 08696-330)',3000),
								 (0,3,'12345678912','2','JOJO TODINHO','Rua Dr. Adhemar Prudente de Moraes, Nº 2719 – Jardim Natal (CEP:08613-135)',5000),
								 (0,4,'12345678913','3','LUCAS PEREIRA','Av. Jaguari, Nº 37 – Cidade Boa Vista (CEP: 08693-110)',800),
								 (0,5,'12345678914','4','MANOEL DAVILA','Rua Adhemar Pereira de Barros, Nº 137 – Parque Maria Helena (CEP: 08683-050)',6500);

SELECT * FROM BANK_CLIENTS, BANK_ACCOUNTS
	WHERE CLIENT_ACCOUNT = ID_ACCOUNT;

# UPDATE BANK_CLIENTS SET NOME = 'MARINA SOUZA' WHERE CLIENT_ACCOUNT = 2;