USE COMPANY;

SELECT * FROM WORKS_ON;
DESC DEPARTAMENT;
-- GERENTE E SEU DEPARTAMENTO
SELECT SSN, F_NAME, D_NAME FROM EMPLOYEE E, DEPARTAMENT D WHERE (E.SSN = D.MGR_SSN);

SHOW TABLES;
-- ALTER TABLE DEPENDENTS CHANGE RELATIOSHIP RELATIONSHIP VARCHAR(15);	
SELECT F_NAME, DEPENDENT_NAME, RELATIONSHIP FROM EMPLOYEE, DEPENDENTS WHERE E_SSN = SSN;

DESC EMPLOYEE;
SELECT B_DATE, ADDRESS FROM EMPLOYEE
	WHERE F_NAME = 'JOHN' AND M_INIT= 'B' AND L_NAME = 'SMITH';

SELECT * FROM DEPARTAMENT WHERE D_NAME = 'RESEARCH';

SELECT F_NAME, L_NAME, ADDRESS FROM EMPLOYEE, DEPARTAMENT
	WHERE D_NAME = 'RESEARCH' AND D_NUMBER=D_NO;

SELECT P_NAME, E_SSN, F_NAME, HOURS
	FROM PROJECT, WORKS_ON, EMPLOYEE
    WHERE P_NUMBER = P_NO;
    
SELECT * FROM DEPARTAMENT;
SELECT * FROM DEPT_LOCATIONS;
DESC DEPARTAMENT;
DESC DEPT_LOCATIONS;

-- ALIAS PARA DESFAZER AMBIGUIDAE OU FACILITAR
SELECT * FROM DEPARTAMENT, DEPT_LOCATIONS WHERE DEPARTAMENT.D_NUMBER = DEPT_LOCATIONS.D_NUMBER;
SELECT * FROM DEPARTAMENT AS D, DEPT_LOCATIONS AS DL WHERE D.D_NUMBER = DL.D_NUMBER;

SELECT CONCAT(F_NAME,' ',L_NAME) AS EMPLOYEE FROM EMPLOYEE;
 
 SELECT F_NAME, L_NAME, SALARY, SALARY*.011 AS INSS FROM EMPLOYEE;
 
 SELECT F_NAME, L_NAME, SALARY, ROUND(SALARY*.011,2) AS INSS FROM EMPLOYEE;
 
 -- LIKE
SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
	WHERE CONSTRAINT_SCHEMA = 'COMPANY' AND
    CONSTRAINT_NAME LIKE '%FK%';
-- 	concat
SELECT CONCAT(F_NAME,' ', L_NAME) AS C_NAME, SALARY, ROUND(SALARY*1.1,2) AS NEW_SALARY 
	FROM EMPLOYEE E, WORKS_ON WO, PROJECT P
	WHERE (E.SSN = WO.E_SSN AND WO.P_NO = P.P_NUMBER AND P.P_NAME='PRODUCTX');
    
SELECT CONCAT(F_NAME, ' ', L_NAME) C_NAME, D_NAME AS DEPARTMENT_NAME FROM EMPLOYEE, DEPARTAMENT
	WHERE (D_NO = D_NUMBER AND ADDRESS LIKE '%HOUSTON%');

-- SUBQUERY

USE COMPANY;

SELECT DISTINCT * FROM PROJECT
	WHERE P_NUMBER IN 
    (SELECT P_NO
    FROM WORKS_ON, EMPLOYEE
    WHERE E_SSN = SSN AND L_NAME = 'SMITH');
    

SELECT CONCAT(F_NAME,' ',L_NAME) NOME FROM EMPLOYEE
	WHERE SSN IN
	(
    SELECT D.E_SSN FROM DEPENDENTS D, WORKS_ON WO
    WHERE D.RELATIONSHIP = 'SPOUSE' AND HOURS BETWEEN 20 AND 30
	); 


SELECT E.F_NAME, E.L_NAME FROM EMPLOYEE E
	WHERE EXISTS (SELECT * FROM DEPENDENTS D
				  WHERE E.SSN = D.E_SSN);

SELECT E.F_NAME, E.L_NAME FROM EMPLOYEE E
	WHERE NOT EXISTS (SELECT * FROM DEPENDENTS D
				  WHERE E.SSN = D.E_SSN);

SELECT E.F_NAME, E.L_NAME FROM EMPLOYEE E
	WHERE EXISTS (SELECT * FROM DEPENDENTS D WHERE E.SSN = D.E_SSN) AND 
		  EXISTS (SELECT * FROM DEPARTAMENT DP WHERE E.SSN = DP.MGR_SSN);

SELECT F_NAME, L_NAME FROM EMPLOYEE 
	WHERE (SELECT COUNT(*) FROM DEPENDENTS WHERE SSN = E_SSN) >=3;
    
SELECT DISTINCT E_SSN FROM WORKS_ON WHERE P_NO IN (1,2,3);
SELECT DISTINCT E_SSN,P_NAME FROM WORKS_ON,PROJECT WHERE P_NO IN (1,2,3) AND P_NUMBER IN (1,2,3);