show databases;
create database  IF NOT EXISTS first_example;
use first_example;
CREATE TABLE IF NOT EXISTS PERSON(
	PERSON_ID SMALLINT UNSIGNED,
	FNAME VARCHAR(20),
	LNAME VARCHAR(20),
	GENDER ENUM('M','F'),
	BIRTH_DATE DATE,
	STREET VARCHAR(30),
	CITY VARCHAR(20),
	STATE VARCHAR(20),
	COUNTRY VARCHAR(20),
	POSTAL_CODE VARCHAR(20),
    CONSTRAINT PK_PERSON PRIMARY KEY (PERSON_ID)
);
# DESC PERSON;
CREATE TABLE IF NOT EXISTS FAVORITE_FOOD (
	PERSON_ID SMALLINT UNSIGNED,
    FOOD VARCHAR(20),
    CONSTRAINT PK_FAVORITE_FOOD PRIMARY KEY (PERSON_ID, FOOD),
    CONSTRAINT FK_FAVORITE_FOOD_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSON(PERSON_ID)
);

SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
	WHERE constraint_schema = 'FIRST_EXAMPLE';

INSERT INTO PERSON VALUES(
	'1','COROLINA','SILVA','F','1979-08-21',
    'RUA 0','CIDADE A', 'SP','MUNDIAL','00000-000'
);

SELECT * FROM PERSON;

DELETE FROM PERSON WHERE PERSON_ID =1;

SELECT * FROM PERSON;

INSERT INTO PERSON VALUES(
	'1','COROLINA','SILVA','F','1979-08-21',
    'RUA 0','CIDADE A', 'SP','MUNDIAL','00000-000'
);

INSERT INTO FAVORITE_FOOD VALUES (1,'LASANHA');

SELECT * FROM FAVORITE_FOOD;

SELECT NOW();

